#!/bin/sh
#cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Body forces to run
g_=( 0.1 0.25  0.5
     1.0  2.5    5
    10.0 20.0 30.0
    40.0 50.0 60.0
    70.0 90.0 100.0)

let ng=2+3*3-1

for i in $(seq 0 ${ng})
do
    # Preprocess
    echo ${g_[i]}
    sed -i "18s/.*/value           (-${g_[i]} 0 0);/" ./constant/g
    # Run the thing
    mpirun -np ${1} simpleFoamMod -parallel > ${2}/log.simpleFoamMod${i}
    # Save results
    mv postProcessing post${i}
done

#------------------------------------------------------------------------------
